/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 *//*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 *//*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 *//*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


package view;

import config.GEoptions;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import viewcontrol.GraphControl;

/**
 *
 * @author Rafael
 */
public class MainFrame extends javax.swing.JFrame {

    private GraphControl GC;

    public GraphControl getGC() {
        return GC;
    }

    public void setGC(GraphControl GC) {
        this.GC = GC;
    }

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        new GEoptions();
        this.setVisible(true);
        this.GC = this.graphPaneContainer.getGP().getGC();
        this.graphPaneContainer.getGP().getGC().setMF(this);
        this.toolPanel.setMF(this);
    }

    public ToolPanel getToolPanel() {
        return this.toolPanel;
    }

    public NavPanel getNavPanel() {
        return this.navPanel;
    }

    public MatrixPanel getMatrixPanel() {
        return this.matrixPanel;
    }

    public PropertiesPanel getPropertiesPanel() {
        return propertiesPanel;
    }

    public MsgPanel getMsgPanel() {
        return msgPanel;
    }

    public void resetButtom() {
        this.toolPanel.resetButtom();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form. WARNING: Do NOT modify this
     * code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PopupMenu = new javax.swing.JPopupMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        CenterPanel = new javax.swing.JPanel();
        graphPaneContainer = new view.GraphPaneContainer();
        NorthPanel = new javax.swing.JPanel();
        toolPanel = new view.ToolPanel();
        SouthPanel = new javax.swing.JPanel();
        msgPanel = new view.MsgPanel();
        EastPanel = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        propertiesPanel = new view.PropertiesPanel();
        matrixPanel = new view.MatrixPanel();
        WestPanel = new javax.swing.JPanel();
        navPanel = new view.NavPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("AAAA");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        PopupMenu.add(jMenu1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));

        jLayeredPane1.setLayout(new java.awt.BorderLayout());

        CenterPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CenterPanel.setPreferredSize(new java.awt.Dimension(100, 200));
        CenterPanel.setLayout(new java.awt.BorderLayout());
        CenterPanel.add(graphPaneContainer, java.awt.BorderLayout.CENTER);

        jLayeredPane1.add(CenterPanel, java.awt.BorderLayout.CENTER);

        NorthPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NorthPanel.setMinimumSize(new java.awt.Dimension(322, 40));
        NorthPanel.setPreferredSize(new java.awt.Dimension(780, 40));
        NorthPanel.setLayout(new java.awt.BorderLayout());
        NorthPanel.add(toolPanel, java.awt.BorderLayout.CENTER);

        jLayeredPane1.add(NorthPanel, java.awt.BorderLayout.NORTH);

        SouthPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SouthPanel.setMinimumSize(new java.awt.Dimension(2, 40));
        SouthPanel.setPreferredSize(new java.awt.Dimension(888, 40));
        SouthPanel.setLayout(new java.awt.BorderLayout());
        SouthPanel.add(msgPanel, java.awt.BorderLayout.CENTER);

        jLayeredPane1.add(SouthPanel, java.awt.BorderLayout.SOUTH);

        EastPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EastPanel.setPreferredSize(new java.awt.Dimension(150, 200));
        EastPanel.setLayout(new javax.swing.BoxLayout(EastPanel, javax.swing.BoxLayout.LINE_AXIS));

        jSplitPane1.setDividerLocation(150);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setRightComponent(propertiesPanel);
        jSplitPane1.setLeftComponent(matrixPanel);

        EastPanel.add(jSplitPane1);

        jLayeredPane1.add(EastPanel, java.awt.BorderLayout.EAST);

        WestPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        WestPanel.setPreferredSize(new java.awt.Dimension(150, 200));
        WestPanel.setLayout(new javax.swing.BoxLayout(WestPanel, javax.swing.BoxLayout.LINE_AXIS));
        WestPanel.add(navPanel);

        jLayeredPane1.add(WestPanel, java.awt.BorderLayout.LINE_START);

        getContentPane().add(jLayeredPane1, java.awt.BorderLayout.CENTER);

        jMenu2.setText("Arquivo");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Editar");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CenterPanel;
    private javax.swing.JPanel EastPanel;
    private javax.swing.JPanel NorthPanel;
    private javax.swing.JPopupMenu PopupMenu;
    private javax.swing.JPanel SouthPanel;
    private javax.swing.JPanel WestPanel;
    private view.GraphPaneContainer graphPaneContainer;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JSplitPane jSplitPane1;
    private view.MatrixPanel matrixPanel;
    private view.MsgPanel msgPanel;
    private view.NavPanel navPanel;
    private view.PropertiesPanel propertiesPanel;
    private view.ToolPanel toolPanel;
    // End of variables declaration//GEN-END:variables
}
