/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Point;

/**
 *
 * @author I839169
 */
public class MsgPanel extends javax.swing.JPanel {

    /**
     * Creates new form MsgPanel
     */
    public MsgPanel() {
        initComponents();
    }

    public void setMsg(String menssagem) {
        this.msgTxt.setText(menssagem);
    }

    public void setPoint(Point P) {
        this.pointLbl.setText(P.toString());
    }

    /**
     * This method is called from within the constructor to
     * initialize the form. WARNING: Do NOT modify this
     * code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msgTxt = new javax.swing.JTextField();
        pointLbl = new javax.swing.JLabel();
        ProgressBar = new javax.swing.JProgressBar();

        setMaximumSize(new java.awt.Dimension(2147483647, 40));
        setMinimumSize(new java.awt.Dimension(600, 40));
        setPreferredSize(new java.awt.Dimension(600, 40));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        msgTxt.setBackground(new java.awt.Color(240, 240, 240));
        msgTxt.setPreferredSize(new java.awt.Dimension(100, 20));
        add(msgTxt);

        pointLbl.setToolTipText("");
        pointLbl.setMaximumSize(new java.awt.Dimension(20, 40));
        pointLbl.setMinimumSize(new java.awt.Dimension(20, 40));
        pointLbl.setPreferredSize(new java.awt.Dimension(60, 40));
        add(pointLbl);
        add(ProgressBar);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JTextField msgTxt;
    private javax.swing.JLabel pointLbl;
    // End of variables declaration//GEN-END:variables
}
