/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import viewcontrol.mode;

/**
 *
 * @author Rafael
 */
public class ToolPanel extends javax.swing.JPanel {
    private MainFrame MF;

    public MainFrame getMF() {
        return MF;
    }

    public void setMF(MainFrame MF) {
        this.MF = MF;
    }    
    /**
     * Creates new form ToolPanel
     */
    public ToolPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddNode = new javax.swing.JButton();
        AddEdge = new javax.swing.JButton();
        Remove = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        AddNode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resouce/Icon-AddNode.png"))); // NOI18N
        AddNode.setMaximumSize(new java.awt.Dimension(40, 40));
        AddNode.setMinimumSize(new java.awt.Dimension(40, 40));
        AddNode.setPreferredSize(new java.awt.Dimension(40, 40));
        AddNode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNodeActionPerformed(evt);
            }
        });
        add(AddNode);

        AddEdge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resouce/Icon-AddAresta.png"))); // NOI18N
        AddEdge.setMaximumSize(new java.awt.Dimension(40, 40));
        AddEdge.setMinimumSize(new java.awt.Dimension(40, 40));
        AddEdge.setPreferredSize(new java.awt.Dimension(40, 40));
        AddEdge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEdgeActionPerformed(evt);
            }
        });
        add(AddEdge);

        Remove.setMaximumSize(new java.awt.Dimension(40, 40));
        Remove.setMinimumSize(new java.awt.Dimension(40, 40));
        Remove.setPreferredSize(new java.awt.Dimension(40, 40));
        add(Remove);

        jButton4.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton4.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton4.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jButton4);

        jButton5.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton5.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton5.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jButton5);

        jButton6.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton6.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton6.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jButton6);

        jButton7.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton7.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton7.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jButton7);

        jButton8.setMaximumSize(new java.awt.Dimension(40, 40));
        jButton8.setMinimumSize(new java.awt.Dimension(40, 40));
        jButton8.setPreferredSize(new java.awt.Dimension(40, 40));
        add(jButton8);
    }// </editor-fold>//GEN-END:initComponents

    private void AddNodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNodeActionPerformed
        this.MF.getGC().setMode(mode.addNode);
    }//GEN-LAST:event_AddNodeActionPerformed

    private void AddEdgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEdgeActionPerformed
        this.MF.getGC().setMode(mode.addEdge);
    }//GEN-LAST:event_AddEdgeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEdge;
    private javax.swing.JButton AddNode;
    private javax.swing.JButton Remove;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    // End of variables declaration//GEN-END:variables
}
